# general settings
name: Enhancement_RLN2_Lf
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100
use_amp: True

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedScene
    baseroot: 'datasets/CL3AN'
    lphase: 'Train'
    geometric_augs: true
    maxsize: 1280

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 6

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [5, 3, 2]             # Batch size per gpu
    iters: [6000, 7000, 7000]
    gt_size: 1280   # Max patch size for progressive training
    gt_sizes: [896, 960, 1088]  # Patch sizes for progressive training.
    # ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedScene
    baseroot: 'datasets/CL3AN'
    lphase: 'Validation'
    geometric_augs: false
    maxsize: 1080

# network structures
network_g:
  type: CC36
  num_blocks: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 150000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [46000, 104000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    # weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 4
  val_freq: !!float 3e3
  save_img: true
  rgb2bgr: true
  use_image: false
  max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 10000
  use_tb_logger: true
  wandb:
    project: low_light
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29800
